"""Full ordered test catalog — 74 acceptance tests.

Sentinels replaced at runtime by run_acceptance.py:
  __FIXTURE_URL__  → file://<tmp_dir>/mock_feed.xml
  __TMP__          → absolute path of the test's tmp dir
"""
from __future__ import annotations

TESTS: list[dict] = [
    # ── global (7) ────────────────────────────────────────────────────────────
    {
        "id": 1, "group": "global", "label": "No args prints help",
        "cmd": ["capcat"],
        "expected_exit": 0, "expected_in_output": ["capcat"],
        "creates_files": False, "needs_init": False, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 2, "group": "global", "label": "--help flag",
        "cmd": ["capcat", "--help"],
        "expected_exit": 0, "expected_in_output": ["Usage"],
        "creates_files": False, "needs_init": False, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 3, "group": "global", "label": "-h flag",
        "cmd": ["capcat", "-h"],
        "expected_exit": 0, "expected_in_output": ["Usage"],
        "creates_files": False, "needs_init": False, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 4, "group": "global", "label": "--version prints version",
        "cmd": ["capcat", "--version"],
        "expected_exit": 0, "expected_in_output": ["capcat"],
        "creates_files": False, "needs_init": False, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 5, "group": "global", "label": "-L logs to file",
        "cmd": ["capcat", "-L", "__TMP__/capcat.log", "fetch", "hn", "--count", "1"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    {
        "id": 6, "group": "global", "label": "-L missing filename exits 1",
        "cmd": ["capcat", "-L"],
        "expected_exit": 1, "expected_in_output": [],
        "creates_files": False, "needs_init": False, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 7, "group": "global", "label": "Unknown command exits 1",
        "cmd": ["capcat", "unknowncmd_xyz"],
        "expected_exit": 1, "expected_in_output": [],
        "creates_files": False, "needs_init": False, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    # ── init (3) ──────────────────────────────────────────────────────────────
    {
        "id": 8, "group": "init", "label": "Fresh init",
        "cmd": ["capcat", "init"],
        "expected_exit": 0, "expected_in_output": ["initialized"],
        "creates_files": False, "needs_init": False, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 9, "group": "init", "label": "Already init'd exits 1",
        "cmd": ["capcat", "init"],
        "expected_exit": 1, "expected_in_output": [],
        "creates_files": False, "needs_init": False, "pre_init": True,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 10, "group": "init", "label": "--reinit on existing succeeds",
        "cmd": ["capcat", "init", "--reinit"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": False, "needs_init": False, "pre_init": True,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    # ── single (9) ────────────────────────────────────────────────────────────
    {
        "id": 11, "group": "single", "label": "No URL prints usage",
        "cmd": ["capcat", "single"],
        "expected_exit": None, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 12, "group": "single", "label": "--help",
        "cmd": ["capcat", "single", "--help"],
        "expected_exit": 0, "expected_in_output": ["Usage"],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 13, "group": "single", "label": "Basic single URL",
        "cmd": ["capcat", "single", "https://en.wikipedia.org/wiki/Markdown"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    {
        "id": 14, "group": "single", "label": "single + --html",
        "cmd": ["capcat", "single", "https://en.wikipedia.org/wiki/Markdown", "--html"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    {
        "id": 15, "group": "single", "label": "single + --media",
        "cmd": ["capcat", "single", "https://en.wikipedia.org/wiki/Markdown", "--media"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    {
        "id": 16, "group": "single", "label": "single + --update",
        "cmd": ["capcat", "single", "https://en.wikipedia.org/wiki/Markdown", "--update"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    {
        "id": 17, "group": "single", "label": "single + --output",
        "cmd": ["capcat", "single", "https://en.wikipedia.org/wiki/Markdown", "--output", "__TMP__/out"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    {
        "id": 18, "group": "single", "label": "single + -V verbose",
        "cmd": ["capcat", "single", "https://en.wikipedia.org/wiki/Markdown", "-V"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    {
        "id": 19, "group": "single", "label": "single + -q quiet",
        "cmd": ["capcat", "single", "https://en.wikipedia.org/wiki/Markdown", "-q"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    # ── fetch (13) ────────────────────────────────────────────────────────────
    {
        "id": 20, "group": "fetch", "label": "No source prints usage",
        "cmd": ["capcat", "fetch"],
        "expected_exit": None, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 21, "group": "fetch", "label": "--help",
        "cmd": ["capcat", "fetch", "--help"],
        "expected_exit": 0, "expected_in_output": ["Usage"],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 22, "group": "fetch", "label": "Single source: hn",
        "cmd": ["capcat", "fetch", "hn", "--count", "3"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    {
        "id": 23, "group": "fetch", "label": "Single source: bbc",
        "cmd": ["capcat", "fetch", "bbc", "--count", "3"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    {
        "id": 24, "group": "fetch", "label": "Single source: lb",
        "cmd": ["capcat", "fetch", "lb", "--count", "3"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    {
        "id": 25, "group": "fetch", "label": "Multi source: hn,bbc",
        "cmd": ["capcat", "fetch", "hn,bbc", "--count", "3"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 90, "fixture": None,
    },
    {
        "id": 26, "group": "fetch", "label": "Three sources: hn,bbc,lb",
        "cmd": ["capcat", "fetch", "hn,bbc,lb", "--count", "3"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 90, "fixture": None,
    },
    {
        "id": 27, "group": "fetch", "label": "fetch + --html",
        "cmd": ["capcat", "fetch", "hn", "--count", "3", "--html"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    {
        "id": 28, "group": "fetch", "label": "fetch + --media",
        "cmd": ["capcat", "fetch", "hn", "--count", "3", "--media"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    {
        "id": 29, "group": "fetch", "label": "fetch + --update",
        "cmd": ["capcat", "fetch", "hn", "--count", "3", "--update"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    {
        "id": 30, "group": "fetch", "label": "fetch + --output",
        "cmd": ["capcat", "fetch", "hn", "--count", "3", "--output", "__TMP__/out"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    {
        "id": 31, "group": "fetch", "label": "fetch + -V verbose",
        "cmd": ["capcat", "fetch", "hn", "--count", "3", "-V"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    {
        "id": 32, "group": "fetch", "label": "fetch + -q quiet",
        "cmd": ["capcat", "fetch", "hn", "--count", "3", "-q"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 60, "fixture": None,
    },
    # ── bundle (14) ───────────────────────────────────────────────────────────
    {
        "id": 33, "group": "bundle", "label": "No name prints usage",
        "cmd": ["capcat", "bundle"],
        "expected_exit": None, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 34, "group": "bundle", "label": "--help",
        "cmd": ["capcat", "bundle", "--help"],
        "expected_exit": 0, "expected_in_output": ["Usage"],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 35, "group": "bundle", "label": "Bundle: tech",
        "cmd": ["capcat", "bundle", "tech", "--count", "3"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 90, "fixture": None,
    },
    {
        "id": 36, "group": "bundle", "label": "Bundle: techpro",
        "cmd": ["capcat", "bundle", "techpro", "--count", "3"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 90, "fixture": None,
    },
    {
        "id": 37, "group": "bundle", "label": "Bundle: news",
        "cmd": ["capcat", "bundle", "news", "--count", "3"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 90, "fixture": None,
    },
    {
        "id": 38, "group": "bundle", "label": "Bundle: science",
        "cmd": ["capcat", "bundle", "science", "--count", "3"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 90, "fixture": None,
    },
    {
        "id": 39, "group": "bundle", "label": "Bundle: ai",
        "cmd": ["capcat", "bundle", "ai", "--count", "3"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 90, "fixture": None,
    },
    {
        "id": 40, "group": "bundle", "label": "Bundle: sports",
        "cmd": ["capcat", "bundle", "sports", "--count", "3"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 90, "fixture": None,
    },
    {
        "id": 41, "group": "bundle", "label": "Bundle: all keyword",
        "cmd": ["capcat", "bundle", "all", "--count", "2"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 120, "fixture": None,
    },
    {
        "id": 42, "group": "bundle", "label": "Bundle: --all flag",
        "cmd": ["capcat", "bundle", "--all", "--count", "2"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 120, "fixture": None,
    },
    {
        "id": 43, "group": "bundle", "label": "bundle + --html",
        "cmd": ["capcat", "bundle", "tech", "--count", "3", "--html"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 90, "fixture": None,
    },
    {
        "id": 44, "group": "bundle", "label": "bundle + --output",
        "cmd": ["capcat", "bundle", "tech", "--count", "3", "--output", "__TMP__/out"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 90, "fixture": None,
    },
    {
        "id": 45, "group": "bundle", "label": "bundle + -V verbose",
        "cmd": ["capcat", "bundle", "tech", "--count", "3", "-V"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": True, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 90, "fixture": None,
    },
    {
        "id": 46, "group": "bundle", "label": "Unknown bundle exits 1",
        "cmd": ["capcat", "bundle", "unknown_bundle_xyz"],
        "expected_exit": 1, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    # ── list (5) ──────────────────────────────────────────────────────────────
    {
        "id": 47, "group": "list", "label": "list (no subcommand)",
        "cmd": ["capcat", "list"],
        "expected_exit": 0,
        "expected_in_output": ["Available sources", "Available bundles"],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 48, "group": "list", "label": "list sources",
        "cmd": ["capcat", "list", "sources"],
        "expected_exit": 0, "expected_in_output": ["Available sources"],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 49, "group": "list", "label": "list bundles",
        "cmd": ["capcat", "list", "bundles"],
        "expected_exit": 0, "expected_in_output": ["Available bundles"],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 50, "group": "list", "label": "list all",
        "cmd": ["capcat", "list", "all"],
        "expected_exit": 0,
        "expected_in_output": ["Available sources", "Available bundles"],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 51, "group": "list", "label": "list --help",
        "cmd": ["capcat", "list", "--help"],
        "expected_exit": 0, "expected_in_output": ["Usage"],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    # ── add-source (4) ────────────────────────────────────────────────────────
    {
        "id": 52, "group": "add-source", "label": "No --url exits 1",
        "cmd": ["capcat", "add-source"],
        "expected_exit": 1, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 53, "group": "add-source", "label": "--help",
        "cmd": ["capcat", "add-source", "--help"],
        "expected_exit": 0, "expected_in_output": ["Usage"],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 54, "group": "add-source", "label": "Valid feed URL (fixture)",
        "cmd": ["capcat", "add-source", "--url", "__FIXTURE_URL__"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": True, "timeout": 60,
        "fixture": "mock_feed.xml",
    },
    {
        "id": 55, "group": "add-source", "label": "Invalid URL (error handling)",
        "cmd": ["capcat", "add-source", "--url", "http://localhost:19999/no-such-feed"],
        "expected_exit": 1, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    # ── remove-source (8) ─────────────────────────────────────────────────────
    {
        "id": 56, "group": "remove-source", "label": "--help",
        "cmd": ["capcat", "remove-source", "--help"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 57, "group": "remove-source", "label": "Interactive (manual)",
        "cmd": ["capcat", "remove-source"],
        "expected_exit": None, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": True, "timeout": 120, "fixture": None,
    },
    {
        "id": 58, "group": "remove-source", "label": "--dry-run",
        "cmd": ["capcat", "remove-source", "--dry-run"],
        "expected_exit": None, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": True, "timeout": 120, "fixture": None,
    },
    {
        "id": 59, "group": "remove-source", "label": "--force",
        "cmd": ["capcat", "remove-source", "--force"],
        "expected_exit": None, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": True, "timeout": 120, "fixture": None,
    },
    {
        "id": 60, "group": "remove-source", "label": "--no-backup",
        "cmd": ["capcat", "remove-source", "--no-backup"],
        "expected_exit": None, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": True, "timeout": 120, "fixture": None,
    },
    {
        "id": 61, "group": "remove-source", "label": "--no-analytics",
        "cmd": ["capcat", "remove-source", "--no-analytics"],
        "expected_exit": None, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": True, "timeout": 120, "fixture": None,
    },
    {
        "id": 62, "group": "remove-source", "label": "--batch (fixture)",
        "cmd": ["capcat", "remove-source", "--batch", "__TMP__/batch_ids.txt"],
        "expected_exit": None, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": True, "timeout": 120,
        "fixture": "batch_ids.txt",
    },
    {
        "id": 63, "group": "remove-source", "label": "--undo latest",
        "cmd": ["capcat", "remove-source", "--undo"],
        "expected_exit": None, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": True, "timeout": 120, "fixture": None,
    },
    # ── generate-config (3) ───────────────────────────────────────────────────
    {
        "id": 64, "group": "generate-config", "label": "--help",
        "cmd": ["capcat", "generate-config", "--help"],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": False, "timeout": 30, "fixture": None,
    },
    {
        "id": 65, "group": "generate-config", "label": "Interactive",
        "cmd": ["capcat", "generate-config"],
        "expected_exit": None, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": True, "timeout": 120, "fixture": None,
    },
    {
        "id": 66, "group": "generate-config", "label": "--output file",
        "cmd": ["capcat", "generate-config", "--output", "__TMP__/myconfig.yaml"],
        "expected_exit": None, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": False, "passthrough": True, "timeout": 120, "fixture": None,
    },
    # ── tui (8) ───────────────────────────────────────────────────────────────
    {
        "id": 67, "group": "tui", "label": "Main Menu → Exit",
        "cmd": ["capcat", "catch"],
        "steps": ["Select \"Exit\""],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": True, "passthrough": False, "timeout": 120, "fixture": None,
    },
    {
        "id": 68, "group": "tui", "label": "bundle → techpro → No HTML → Back → Exit",
        "cmd": ["capcat", "catch"],
        "steps": [
            "Select \"Catch articles from a bundle of sources\"",
            "Select \"techpro\"",
            "Choose \"No\" for HTML",
            "In completion screen choose \"Back to Main Menu\"",
            "Choose \"Exit\"",
        ],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": True, "passthrough": False, "timeout": 120, "fixture": None,
    },
    {
        "id": 69, "group": "tui", "label": "bundle → tech → Yes HTML → Exit",
        "cmd": ["capcat", "catch"],
        "steps": [
            "Select \"Catch articles from a bundle of sources\"",
            "Select \"tech\"",
            "Choose \"Yes\" for HTML",
            "In completion screen choose \"Exit\"",
        ],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": True, "passthrough": False, "timeout": 120, "fixture": None,
    },
    {
        "id": 70, "group": "tui", "label": "fetch multi-select hn+bbc → No HTML → Back → Exit",
        "cmd": ["capcat", "catch"],
        "steps": [
            "Select \"Catch articles from a list of sources\"",
            "Space-select hn and bbc, press Enter",
            "Choose \"No\" for HTML",
            "In completion screen choose \"Back to Main Menu\"",
            "Choose \"Exit\"",
        ],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": True, "passthrough": False, "timeout": 120, "fixture": None,
    },
    {
        "id": 71, "group": "tui", "label": "single source → hn → No HTML → Back → Exit",
        "cmd": ["capcat", "catch"],
        "steps": [
            "Select \"Catch from a single source\"",
            "Select \"hn\"",
            "Choose \"No\" for HTML",
            "In completion screen choose \"Back to Main Menu\"",
            "Choose \"Exit\"",
        ],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": True, "passthrough": False, "timeout": 120, "fixture": None,
    },
    {
        "id": 72, "group": "tui", "label": "single URL → https://en.wikipedia.org/wiki/Markdown → No HTML → Back → Exit",
        "cmd": ["capcat", "catch"],
        "steps": [
            "Select \"Catch a single article by URL\"",
            "Type: https://en.wikipedia.org/wiki/Markdown  then press Enter",
            "Choose \"No\" for HTML",
            "In completion screen choose \"Back to Main Menu\"",
            "Choose \"Exit\"",
        ],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": True, "passthrough": False, "timeout": 120, "fixture": None,
    },
    {
        "id": 73, "group": "tui", "label": "Manage Sources → List → browse → back → Exit",
        "cmd": ["capcat", "catch"],
        "steps": [
            "Select \"Manage Sources (add/remove/configure)\"",
            "Select \"List All Sources\"",
            "Browse the list, then select \"Back to Source Management\"",
            "Select \"Back to Main Menu\"",
            "Select \"Exit\"",
        ],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": True, "passthrough": False, "timeout": 120, "fixture": None,
    },
    {
        "id": 74, "group": "tui", "label": "Manage Sources → Add RSS → type fixture URL → back → Exit",
        "cmd": ["capcat", "catch"],
        "steps": [
            "Select \"Manage Sources (add/remove/configure)\"",
            "Select \"Add New Source from RSS Feed\"",
            "Type the fixture URL shown above, press Enter",
            "Press Enter to continue",
            "Select \"Back to Main Menu\"",
            "Select \"Exit\"",
        ],
        "expected_exit": 0, "expected_in_output": [],
        "creates_files": False, "needs_init": True, "pre_init": False,
        "is_tui": True, "passthrough": False, "timeout": 120,
        "fixture": "mock_feed.xml",
    },
]
